### ISSUE TITLE
Order of options

### ISSUE THREAD

**Issue by nxg** [mafm/zfs-snapshot-disk-usage-matrix#5]
Line 63 is

    cmd = "{} zfs list -r -t snapshot -s creation '{}' -o name".format(maybe_ssh(host), filesystem)

This has the `-o name` option _after_ the filesystem name, which breaks the `zfs` command on FreeBSD (it complains about the absence of filesystems `-o` and `name`).  Moving this option before the `'{}'` fixes the problem.

**Comment by mafm** [comment]
Thanks for pointing this out.

If you want to send me a pull request, I'll merge it.

Otherwise, I'll try to fix it some time next week.

**Comment by nxg** [comment]
Et voilà...

**Comment by mafm** [comment]
Thanks!
